# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangpython3.5
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython3.5
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JlFZXCMU0LVrUr9alOjfjmYaZi3D1smYbss9cykb7AZ7lDL/uVK/e7Hm8fNSEL/CYeDsqS1xt6o2xKQtEAkV+JFvQvKKuFMIxKlkHknR3fEjHE/Um3jKzI1MGnrW2OWH4rtw37Yj7lS5qYnRg2K8RLixTtkqW0RSh6mVF8rIpawqMbOS1rBlQKOeRG+2ryaz7g0lmRFyzZQPQY0YgjReJmpNRLkxtX+8rJoIjOD8m3C756GF5QN8wZGedesvji1js+KkMUb5LiAPL2yfaHIcz9qR6XawxZ0PRbgGB5kp1ApFEI6EKRszPD4IznMoSDRmptJDZxNIWgjgyx41izm26ZBeIAbsDyPpMu1pZzHrQhpuK+UBqQ6J18ll/tbNza+tkXlhfih6HQV8hvTKEd10gn8GVlDNpynFSo7iq0G40yTRV3YavPmpa6GZax+RJDPiB5hY1EVGx1ZfxD7QZcZfAJBhsQb38bSqHia9/REX0qm4mhTE3rB0IICZn3/YHHHPRI5j/liOO3ZPIq0YfCfm8j0SdGTWEZhbpBIH+RIKj0pv79lxLxMabtiDefMGGRaowWK+6UlyA1GzWrDgYEywYA6YSgxcbf9bVWIL3SF1D5tOPLmy3QiQY84lYBqqdQVL79VZP7ANOj/iuAd9b764kqz1HMG64vNQRQb1Kx3JTuM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml