travis:
  secure:
    BINSTAR_TOKEN: BYPXc7djmcD4WVhkI/mdShi7ojDTKKkRf0PMvMhMOvVsZuJM8hI0bBxDu9ZZAkQEBPIwkZMHGxpCgYnhmLrLZa3UtoLVkIvt09DuYX9J87hrIsLl8lKlyKSRRJHClty/53Sysjd9EJleC8dXa1yFqHlh/Lj3/0GcrmhLjxafIUR/XxdqNq1OBy6kjhFTVAM52fRqEcm0BD/AHWkzXMmwjE2XFDFVonrfsqHqliHYOiRvp9YlsD+B10pbyKEu1tJ8ntvwTN8FgkdJwOKqVEZD4Gd4H3IdfkBVSXWHUCDxomCD2K9jNf/2TKlMZYQVBcZ8h38uW6734wFIU5m20X4yNxOSciZjHl/2T+zCd1UKlic7zaaDW0w+a7kmogrRMzQyxdUiZCK5EX1nafPcKpz7RvDMfsOwgl6IU6tLVNViVOXmHiMHNpV1FZoddt5zH9K509dnx48j5V2GpXXGjLnNXPPRBO7FnKOQWS//cJUyRTIYdvDyPMl992e+5ESg7Tmxg6Ad+3LSyHDOl3bN9GQwxOFJ98yoDdkrRjSZD0zyr9z7RgGKcaEIHs7iCtxsVS8MjgsWWw3DgZ/LFr7apZiJrcgd6LTNO7wm/vOVdtZMih6rmPWlpGX4Kiik+8G3hHB4vqD6j09XmVXC+FKuL2CCziLAyM2aN/87bGcqY4O2azc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
