appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JlFZXCMU0LVrUr9alOjfjmYaZi3D1smYbss9cykb7AZ7lDL/uVK/e7Hm8fNSEL/CYeDsqS1xt6o2xKQtEAkV+JFvQvKKuFMIxKlkHknR3fEjHE/Um3jKzI1MGnrW2OWH4rtw37Yj7lS5qYnRg2K8RLixTtkqW0RSh6mVF8rIpawqMbOS1rBlQKOeRG+2ryaz7g0lmRFyzZQPQY0YgjReJmpNRLkxtX+8rJoIjOD8m3C756GF5QN8wZGedesvji1js+KkMUb5LiAPL2yfaHIcz9qR6XawxZ0PRbgGB5kp1ApFEI6EKRszPD4IznMoSDRmptJDZxNIWgjgyx41izm26ZBeIAbsDyPpMu1pZzHrQhpuK+UBqQ6J18ll/tbNza+tkXlhfih6HQV8hvTKEd10gn8GVlDNpynFSo7iq0G40yTRV3YavPmpa6GZax+RJDPiB5hY1EVGx1ZfxD7QZcZfAJBhsQb38bSqHia9/REX0qm4mhTE3rB0IICZn3/YHHHPRI5j/liOO3ZPIq0YfCfm8j0SdGTWEZhbpBIH+RIKj0pv79lxLxMabtiDefMGGRaowWK+6UlyA1GzWrDgYEywYA6YSgxcbf9bVWIL3SF1D5tOPLmy3QiQY84lYBqqdQVL79VZP7ANOj/iuAd9b764kqz1HMG64vNQRQb1Kx3JTuM=}
